# Introduction of Numpy

In [8]:
import numpy as np

In [9]:
old_list = [1, 2, 3]
new_list = []
for el in old_list:
    new_list.append(el * 2)
    
new_list

[2, 4, 6]

In [13]:
new_list = [y * 2 for y in old_list]
new_list

[2, 4, 6]

In [15]:
new_list = list(map(lambda x: x*2, old_list))
new_list

[2, 4, 6]

In [18]:
list(map(lambda x: x*2, old_list))

[2, 4, 6]

In [50]:
set(map(lambda x: x*2, old_list))


{2, 4, 6}

In [23]:
lambda x: x * 2

<function __main__.<lambda>(x)>

In [25]:
%%timeit
[el * 2 for el in list(range(0, 10))]

1.1 µs ± 6.51 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [27]:
# in arrays, all the elements should be exactaly the same data types
data = np.arange(12)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
data.dtype

dtype('int64')

In [30]:
data.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [31]:
np.append(data, 22)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 22])

In [32]:
data.size

12

In [33]:
data.shape

(12,)

In [34]:
data.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
data.shape

(12,)

In [36]:
data2 = data.reshape(3, 4)
data2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [38]:
data2.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [39]:
np.transpose(data2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [40]:
np.transpose?

Signature: np.transpose(a, axes=None)
Docstring:
Permute the dimensions of an array.

Parameters
----------
a : array_like
    Input array.
axes : list of ints, optional
    By default, reverse the dimensions, otherwise permute the axes
    according to the values given.

Returns
-------
p : ndarray
    `a` with its axes permuted.  A view is returned whenever
    possible.

See Also
--------
moveaxis
argsort

Notes
-----
Use `transpose(a, argsort(axes))` to invert the transposition of tensors
when using the `axes` keyword argument.

Transposing a 1-D array returns an unchanged view of the original array.

Examples
--------
>>> x = np.arange(4).reshape((2,2))
>>> x
array([[0, 1],
       [2, 3]])

>>> np.transpose(x)
array([[0, 2],
       [1, 3]])

>>> x = np.ones((1, 2, 3))
>>> np.transpose(x, (1, 0, 2)).shape
(2, 1, 3)
File:      ~/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py
Type:      function


In [42]:
data2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.max(data2, axis = 0)

array([ 8,  9, 10, 11])

In [44]:
np.max(data2, axis = 0, keepdims = True)

array([[ 8,  9, 10, 11]])

In [41]:
np.max(data2, axis = 1)

array([ 3,  7, 11])

In [45]:
np.max(data2, axis = 1, keepdims = True)

array([[ 3],
       [ 7],
       [11]])

In [46]:
np.random.randint(1, 10, size = [5, 5])

array([[2, 6, 4, 9, 7],
       [6, 7, 2, 1, 3],
       [9, 1, 6, 1, 9],
       [2, 7, 3, 7, 4],
       [6, 7, 2, 1, 1]])